### ISSUE TITLE
yo generator

### ISSUE THREAD

**Issue by hzlmn** [WhitestormJS/generator-whs-plugin#1]
Hi @sasha240100 , maybe it is a better option to make it as a`Yeoman` generator ?
Basically typing `yo whs-plugin` is much easier than following hustle with clone, changing files etc.

**Comment by sasha240100** [comment]
@hzlmn Possible. Can you provide more information about process with `Yeoman` ?

**Comment by sasha240100** [comment]
@hzlmn Pull request is also acceptable

**Comment by hzlmn** [comment]
It's pretty straight-forward to built it see here http://yeoman.io/authoring/.
I can make one, but I need more clarification about structure, like would be `Gulp` only one choice or `Grunt` and friends could be added as well. Same for `webpack`.

**Comment by sasha240100** [comment]
@hzlmn `Grunt` and friends are welcome. Can't say it about `webpack` - there i doubt. Let's start with `Gulp` and `Grunt` and after it - add ability to choose between webpack, rollup and browserify (next step)

**Comment by typedef42** [comment]
also what about [jspm](http://jspm.io/) and [system.js](https://github.com/systemjs/systemjs) as dependency manager ? these are cool and also used by [aurelia.io](http://aurelia.io)

**Comment by sasha240100** [comment]
@typedef42 Where can we use them?
@hzlmn What anout pull request? Will you make it or it is just a proposed idea?

**Comment by typedef42** [comment]
@sasha240100 it a bit a work, but it could provide a webpack alternative to build whitestorm.js and its dependencies.
What I have in mind is what the aurelia.io team does, they provide different skeleton/seed applications for their framework. One example using webpack, one using jspm etc. [aurelia-skeleton-repo](https://github.com/aurelia/skeleton-navigation)
We don't really need to have multiple build tool-chain for the whitestorm.js project though.

**Comment by sasha240100** [comment]
@typedef42 [WhitestormJS/test-whitestorm-webpack](https://github.com/WhitestormJS/test-whitestorm-webpack) would be a nice addition to such skeleton. Yep, you may add this TODO as issue in Whitestorm.js repo

**Comment by hzlmn** [comment]
@sasha240100 Yes, I will submit it in the evening today.

**Comment by sasha240100** [comment]
@hzlmn Have you made it?

**Comment by sasha240100** [comment]
@hzlmn Tell me if something is wrong. I willtry to do it instead of you

**Comment by sasha240100** [comment]
@hzlmn @typedef42 Started migrating to yeoman. Will upload some updates later today.
